<?php

namespace GestionBundle\Repository\comunicacion;

/**
 * OrdenInformadaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdenInformadaRepository extends \Doctrine\ORM\EntityRepository
{
}
