<?php

namespace GestionBundle\Repository\rrhh;

/**
 * TipoUnidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConductorRepository extends \Doctrine\ORM\EntityRepository
{
	public function getConductoresEmpresa(\AppBundle\Entity\Empresa $empresa) 
	{ 
			return $this->createQueryBuilder('c')
						->where('c.empresa = :empresa')
						->setParameter('empresa', $empresa)
						->orderBy('c.apellido')
						->getQuery()
						->getResult();
	} 
}
