<?php

namespace AppBundle\Repository;

/**
 * EmpresaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmpresaRepository extends \Doctrine\ORM\EntityRepository
{

	public function getEmpresaWithCodigo($codigo)
	{
		  $query = $this->getEntityManager()
			            ->createQuery(
			                			'SELECT e 
			                			 FROM AppBundle:Empresa e 
			                			 WHERE e.codigo = :codigo'
			            			  )
			            ->setParameter('codigo', $codigo);

		  return $query->getOneOrNullResult();
	}
}
