<?php

namespace GestionBundle\Repository\trafico;

/**
 * OrdenServicioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdenServicioRepository extends \Doctrine\ORM\EntityRepository
{

	public function getOrdenesServicioEmpresa(\AppBundle\Entity\Empresa $empresa, $fecha) 
	{ 
			return $this->createQueryBuilder('o')
						->join('o.turno', 't')
						->join('t.servicio', 's')
						->join('s.cliente', 'c')
						->where('s.empresa = :empresa')
						->andWhere('o.activa = :activa')
						->andWhere('o.fecha = :fecha')
						->setParameter('empresa', $empresa)
						->setParameter('activa', true)
						->setParameter('fecha', $fecha)
						->orderBy('c.razonSocial')
						->addOrderBy('s.nombre')
						->getQuery()
						->getResult();
	} 
}
