<?php

namespace GestionBundle\Repository\ventas;

/**
 * CiudadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CiudadRepository extends \Doctrine\ORM\EntityRepository
{

	public function getCiudadesEmpresa(\AppBundle\Entity\Empresa $empresa) 
	{ 
			return $this->createQueryBuilder('c')
						->where('c.empresa = :empresa')
						->setParameter('empresa', $empresa)
						->orderBy('c.nombre')
						->getQuery()
						->getResult();
	} 
}
