<?php

namespace GestionBundle\Repository\ventas;

/**
 * ClienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClienteRepository extends \Doctrine\ORM\EntityRepository
{
	public function getClientesEmpresa(\AppBundle\Entity\Empresa $empresa) 
	{ 
			return $this->createQueryBuilder('c')
						->where('c.empresa = :empresa')
						->setParameter('empresa', $empresa)
						->orderBy('c.razonSocial')
						->getQuery()
						->getResult();
	} 
}
